# Project: karatsuba
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = karatsuba.o
LINKOBJ  = karatsuba.o
LIBS     = -L"C:/CONY/Dev-c++/Dev-Cpp/MinGW64/lib" -L"C:/CONY/Dev-c++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/CONY/Dev-c++/Dev-Cpp/MinGW64/include" -I"C:/CONY/Dev-c++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/CONY/Dev-c++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/CONY/Dev-c++/Dev-Cpp/MinGW64/include" -I"C:/CONY/Dev-c++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/CONY/Dev-c++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/CONY/Dev-c++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = karatsuba.exe
CXXFLAGS = $(CXXINCS) -std=gnu++11
CFLAGS   = $(INCS) -std=gnu++11
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

karatsuba.o: karatsuba.cpp
	$(CPP) -c karatsuba.cpp -o karatsuba.o $(CXXFLAGS)
